# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  host: db
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
development:
  <<: *default
  database: ProjetoBilinho_development
test:
  <<: *default
  database: ProjetoBilinho_test
production:
  <<: *default
  database: ProjetoBilinho_production
